// Source preservation and interaction regression checks for the A3 / 44 workbench.
import {JSDOM} from '/private/tmp/haven-plan-tests/node_modules/jsdom/lib/api.js';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const root=path.resolve('bashkent-local/site');
const data=JSON.parse(await fs.readFile(root+'/assets/plans/haven44/workbench.json','utf8'));
const audit=JSON.parse(await fs.readFile('output/plan-studies/a3-type44/geometry-audit.json','utf8'));
const html=await fs.readFile(root+'/apartment.html','utf8');
const js=await fs.readFile(root+'/apartment.js','utf8');
const dom=new JSDOM(html,{url:'http://localhost:8080/apartment.html?style=graphite',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
const css=d.createElement('style');css.textContent=await fs.readFile(root+'/apartment.css','utf8');d.head.append(css);
const $=s=>d.querySelector(s),click=s=>$(s).click();
const settle=()=>new Promise(resolve=>setTimeout(resolve,20));
let printed=0,exportBlob,clipboard='';
w.fetch=async url=>({ok:true,json:async()=>JSON.parse(await fs.readFile(path.join(root,url),'utf8'))});
w.URL.createObjectURL=blob=>{exportBlob=blob;return 'blob:local-test'};
w.URL.revokeObjectURL=()=>{};
w.HTMLAnchorElement.prototype.click=function(){};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
w.HTMLDialogElement.prototype.close=function(){this.open=false};
w.print=()=>printed++;
d.fonts={ready:Promise.resolve()};
Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>{clipboard=text}}});
w.DOMPoint=class{constructor(x,y){this.x=x;this.y=y}matrixTransform(){return this}};
w.eval(js);
for(let n=0;n<100&&!$('#drawing>svg');n++)await settle();
assert.ok($('#drawing>svg'),'plan loaded');
const actual=[...d.querySelectorAll('#drawing [data-source-seq]')];
assert.equal(actual.length,889);
const expected=new Map(audit.paths.map(p=>[String(p.seqno),p]));
for(const p of actual){const original=expected.get(p.dataset.sourceSeq);assert.ok(original);assert.equal(p.getAttribute('d'),original.d);assert.equal(p.dataset.cadLayer,original.layer)}
const source=await fs.readFile(root+'/assets/plans/haven44/source.pdf');
assert.equal(crypto.createHash('sha256').update(source).digest('hex'),audit.source_sha256);
assert.equal(data.blocks.length,11);
assert.equal(new Set(data.blocks.map(b=>b.id)).size,11);
assert.equal(data.rooms.length,7);
assert.equal(Math.round(data.rooms.reduce((sum,r)=>sum+Number(r.area.replace(',','.')),0)*100),9246);
assert.equal(d.querySelectorAll('script[src]').length,1);
assert.ok(!html.includes('apartment-3d.js'));
for(const id of ['furniture','dimensions']){click('#'+id+'-toggle');assert.ok($('#drawing').classList.contains('hide-'+id));click('#'+id+'-toggle');assert.ok(!$('#drawing').classList.contains('hide-'+id))}
assert.equal($('#style-select'),null);assert.equal(d.body.dataset.style,'sand');assert.equal(new URL(w.location.href).searchParams.has('style'),false);
click('[data-floor="6"]');assert.match($('#drawing-subtitle').textContent,/этаж 6/);
click('[data-floor="4"]');
click('.room-row[data-room="living"]');assert.equal($('#focus-name').textContent,'Гостиная');assert.equal($('#focus-area').textContent,'21,49 м²');
click('#clear-room');assert.equal($('#room-focus').hidden,true);
const box=$('#drawing>svg').getAttribute('viewBox');assert.equal($('.zoom-controls').hidden,true);assert.equal($('#zoom-in').disabled,true);
click('#zoom-in');assert.equal($('#drawing>svg').getAttribute('viewBox'),box);
const wheel=new w.WheelEvent('wheel',{deltaY:180,bubbles:true,cancelable:true});$('#drawing>svg').dispatchEvent(wheel);assert.equal(wheel.defaultPrevented,false);assert.equal($('#drawing>svg').getAttribute('viewBox'),box);
for(const key of ['+','-','0'])d.body.dispatchEvent(new w.KeyboardEvent('keydown',{key,bubbles:true}));assert.equal($('#drawing>svg').getAttribute('viewBox'),box);
for(const block of data.blocks){$('#block-select').value=block.id;$('#block-select').dispatchEvent(new w.Event('change'));assert.equal($('#drawing-title').textContent,'Секция '+block.id);assert.ok(d.querySelectorAll('#drawing .floor-architecture path').length>100)}
click('#tab-complex');assert.equal(d.querySelectorAll('#drawing [data-block]').length,11);
click('#tab-apartment');assert.equal($('#block-select').value,'A3');
assert.equal($('#ruler-toggle'),null);assert.equal($('#source-toggle'),null);assert.equal($('#source-controls'),null);
click('#fullscreen-toggle');assert.ok($('.drawing-panel').classList.contains('expanded'));d.body.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.ok(!$('.drawing-panel').classList.contains('expanded'));
click('#favorite-toggle');assert.equal($('#favorite-toggle').getAttribute('aria-pressed'),'true');assert.ok(w.localStorage.getItem('haven44:favorites').includes('A3-44-4'));click('#favorite-toggle');
click('.source-trigger');assert.equal($('#source-dialog').open,true);click('#source-dialog .dialog-close');assert.equal($('#source-dialog').open,false);
click('#light-trigger');click('#show-balcony');assert.equal($('#light-dialog').open,false);assert.equal($('#focus-name').textContent,'Балкон');
click('#copy-link');await settle();assert.equal(clipboard,w.location.href);assert.ok(clipboard.includes('room=balcony'));
click('#download-svg');await settle();assert.ok(exportBlob);const text=await new Promise(resolve=>{const r=new w.FileReader();r.onload=()=>resolve(r.result);r.readAsText(exportBlob)});
const saved=new JSDOM(text,{contentType:'image/svg+xml'}).window.document;
assert.equal(saved.querySelectorAll('[data-source-seq]').length,889);
assert.equal(saved.querySelector('svg').getAttribute('viewBox'),data.planView.join(' '));
click('#print-plan');await settle();assert.equal(printed,1);assert.equal(d.querySelectorAll('#print-sheet [data-source-seq]').length,889);
dom.window.close();
console.log('PASS: 889 original paths + source PDF hash; 11 sections; 7 room areas; fixed HAVEN 02 style; floor selection; furniture/dimensions; room selection; fixed 2D fit / native wheel; no ruler/comparison controls; expand/Escape; favorite; dialogs; URL link; SVG and print preparation.');
console.log('Browser rendering and actual downloads are checked separately. Print OS dialog / physical output and touch pinch require manual device checks.');
